#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Custom for my own machine. I do think that it is just a workaround. But for now, idk that much about gradle and
# I haven't looked into it yet. Following is warning when I synced gradle:
#   The following Kotlin/Native targets cannot be built on this machine and are disabled:
#   iosArm64, iosSimulatorArm64, iosX64
#   To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.
# It probably requires completely removing editing out the native IOS modules or something.
kotlin.native.ignoreDisabledTargets=true